# -*- coding: utf-8 -*-
"""Health AI

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1d5lReGGsQvgIq6Rja0GXQORKhd3ubEQ4
"""

# Install libraries
!pip install gradio torch transformers -q

import gradio as gr

# --- Symptoms Mapping for Prediction ---
symptom_map = {
    "fever": "Viral Infection / Flu",
    "cough": "Common Cold / Bronchitis",
    "headache": "Migraine / Stress",
    "chest pain": "Heart related issue (Consult Doctor)",
    "stomach pain": "Gastritis / Indigestion",
    "sore throat": "Throat Infection / Flu",
    "fatigue": "Anemia / Stress / Lack of sleep",
    "body pain": "Viral Fever / Dehydration",
    "cold": "Allergy / Viral Cold",
    "shortness of breath": "Asthma / Lung related issue"
}

# --- Main Health AI Function ---
def health_ai(name, age, gender, height, weight, activity_level, symptoms):
    # BMI Calculation
    bmi = weight / (height ** 2)
    if bmi < 18.5:
        bmi_status = "⚠️ Underweight"
    elif 18.5 <= bmi < 24.9:
        bmi_status = "✅ Normal"
    elif 25 <= bmi < 29.9:
        bmi_status = "⚠️ Overweight"
    else:
        bmi_status = "⚠️ Obese"

    # Calories Calculation (Mifflin-St Jeor formula simplified)
    if gender == "Male":
        calories = 10 * weight + 6.25 * (height*100) - 5 * age + 5
    else:
        calories = 10 * weight + 6.25 * (height*100) - 5 * age - 161

    # Adjust for activity
    activity_factor = {"Low":1.2, "Medium":1.55, "High":1.9}
    daily_calories = calories * activity_factor[activity_level]

    # Water intake
    water_intake = weight * 35

    # Sleep recommendation
    if age < 18:
        sleep = "8–10 hours"
    elif 18 <= age <= 60:
        sleep = "7–9 hours"
    else:
        sleep = "7–8 hours"

    # Exercise Suggestion
    if bmi < 18.5:
        exercise = "Light Yoga, Walking, avoid over-exertion."
        diet = "High protein food: eggs, milk, nuts, banana, rice, potatoes."
    elif 18.5 <= bmi < 24.9:
        exercise = "30 mins Jogging/Walking/Swimming daily."
        diet = "Balanced diet: vegetables, fruits, dal, chapati, rice."
    elif 25 <= bmi < 29.9:
        exercise = "Brisk walking, cycling, yoga (40 mins daily)."
        diet = "Reduce sugar & oil, eat greens, oats, millets."
    else:
        exercise = "Consult doctor. Start with light yoga & walking."
        diet = "Strict control, avoid fast food & sweets."

    # Mental Health Tip
    mental_tip = "Practice 10 mins meditation daily & maintain gratitude journal."

    # Symptom Analysis
    symptoms = symptoms.lower()
    predictions = []
    for s, condition in symptom_map.items():
        if s in symptoms:
            predictions.append(f"- {s.title()} → Possible: {condition}")
    if not predictions and symptoms.strip() != "":
        predictions.append("❓ No clear match found. Please consult a doctor.")
    elif symptoms.strip() == "":
        predictions.append("❓ No symptoms entered.")

    # Final Result
    result = f"""
👤 Name: {name} | 🧑 Gender: {gender} | 🎂 Age: {age}
📏 Height: {height} m | ⚖️ Weight: {weight} kg

📊 BMI: {bmi:.2f} → {bmi_status}
🔥 Daily Calorie Needs: {daily_calories:.0f} kcal
💧 Water Intake: {water_intake:.0f} ml/day
😴 Sleep Recommendation: {sleep}
🥗 Diet Suggestion: {diet}
🏃 Exercise Suggestion: {exercise}
🧘 Mental Health Tip: {mental_tip}

🔎 Symptom Analysis:
{chr(10).join(predictions)}

⚠️ Disclaimer: This is for **informational purposes only**.
Always consult a qualified healthcare professional for accurate medical advice.
This is just an AI prediction based on given data.
"""
    return result

# --- Gradio UI ---
demo = gr.Interface(
    fn=health_ai,
    inputs=[
        gr.Textbox(label="Name"),
        gr.Number(label="Age"),
        gr.Dropdown(["Male", "Female"], label="Gender"),
        gr.Number(label="Height (in meters)"),
        gr.Number(label="Weight (in kg)"),
        gr.Dropdown(["Low", "Medium", "High"], label="Activity Level"),
        gr.Textbox(label="Enter Symptoms (comma separated)", placeholder="Example: fever, cough, headache")
    ],
    outputs="text",
    title="🩺 Complete Health AI Assistant",
    description="Get BMI, Calories, Water, Sleep, Diet, Exercise, Mental Health Tips & Symptom Predictions."
)

demo.launch()